# Generated by Django 4.1.1 on 2022-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_resume_job_profile_alter_resume_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
