# Generated by Django 4.1.1 on 2022-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_resume_job_profile_alter_resume_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
